name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Run Tests
      run: xcodebuild -scheme Turbo test -quiet -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14'
